// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with [Firebase.initializeApp].
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTlrKycJRtWAU7mRzlfrCEeC6GCWgQERA',
    appId: '1:514446176088:web:974e860df1810804f33f2d',
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    authDomain: 'vvc-app-845aa.firebaseapp.com',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
    measurementId: 'G-LNS1VD75JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANU20JRJtAhvsssXNvWe5q5nJ3XzXuzXw',
    appId: '1:514446176088:android:32a1be58e240c63ff33f2d',
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANU20JRJtAhvsssXNvWe5q5nJ3XzXuzXw',
    appId: '1:514446176088:ios:32a1be58e240c63ff33f2d', // Placeholder
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
    iosBundleId: 'com.vvc.vvcAttendance',
  );
}
