// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0to_fSuGnPOWiIICFdkNpQaqDko6IjOM',
    appId: '1:514446176088:web:974e860df1810804f33f2d',
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    authDomain: 'vvc-app-845aa.firebaseapp.com',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
    measurementId: 'G-LNS1VD75JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANU20JRJtAhvsssXNvWe5q5nJ3XzXuzXw',
    appId: '1:514446176088:android:32a1be58e240c63ff33f2d',
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANU20JRJtAhvsssXNvWe5q5nJ3XzXuzXw',
    appId: '1:514446176088:ios:d6630707edc01888f33f2d',
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
    iosBundleId: 'com.vvc.vvcAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLNv5vkF6Nuv_Ybssrb5PYSUlyksEoHg',
    appId: '1:514446176088:ios:76132cabbca60904f33f2d',
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
    iosBundleId: 'vvc-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0to_fSuGnPOWiIICFdkNpQaqDko6IjOM',
    appId: '1:514446176088:web:7af6733ff9ce7365f33f2d',
    messagingSenderId: '514446176088',
    projectId: 'vvc-app-845aa',
    authDomain: 'vvc-app-845aa.firebaseapp.com',
    storageBucket: 'vvc-app-845aa.firebasestorage.app',
    measurementId: 'G-NTZ0G1C1FC',
  );
}
